resume:  #'/public/home/ock/ActionCLIP/clip_models/vit16_8f/model_best.pt'
pretrain: 
seed: 1024
data:
    dataset: kinetics400
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 32
    workers: 16
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg'
    train_list: '/public/home/ock/ActionCLIP/lists/k4001/train_frames_new.txt' #'/public/home/ock/ActionCLIP/lists/k4001/train_frames_new.txt'#
    val_list: 'lists/k4001/val_frames_re.txt' 
    label_list: 'lists/kinetics_400_labels.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 0  #2
        M: 0 #9
    random_shift: False
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_k400
    sim_header: "Transf"  #Transf   meanP  LSTM Conv_1D Transf_cls
    joint: False
    describe:
solver:
    type: cosine
    epochs: 50
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.3
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: false
    ratio: 0
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1