resume:  exp/clip_k400/ViT-B/32/kinetics400/20211202_145935/last_model.pt #exp/clip_k400/ViT-B/32/kinetics400/20211202_150642/last_model.pt #exp/clip_k400/ViT-B/32/kinetics400/20211201_203709/last_model.pt
pretrain:
seed: 1024
data:
    dataset: kinetics400
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 48
    workers: 16
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg'
    train_list: 'lists/k4001/train_frames_new.txt'
    val_list: 'lists/k4001/val_frames_re.txt' #
    label_list: 'lists/kinetics_400_labels.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 2 #2
        M: 9  #9
    random_shift: True
network:
    arch: ViT-B/32  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_k400
    sim_header: "Transf"  #Transf   meanP  LSTM Conv_1D Transf_cls
    joint: False
    describe:
swin_model:
    in_channels: 1024
    type: 'base'
    pretrain: './clip_models/swin_base_patch4_window7_224_22k.pth'
    pretrain_type: '2D_pretrain'
    patch_size: [2,4,4]
    window_size: [8,7,7]
    drop_path_rate: 0.2
    depths: [2,2,18,2]
    embed_dim: 128
    num_heads: [4,8,16,32]
solver:
    type: cosine
    epochs: 50
    start_epoch: 11
    epoch_offset: 0
    optim: adamw
    swin_lr: 3.e-5
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.05 #0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: False
    decay_mult: 0
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1