resume:
pretrain:
seed: 1024
data:
    dataset: sthv2
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 24
    workers: 16
    num_classes: 174
    image_tmpl: '{:06d}.jpg'
    train_list: '/public/datasets/something/something_v2/something_v2_2/something_v2_rgb_train2.txt'  #'/public/home/ock/ActionCLIP/lists/k4001/train_frames_new.txt'#
    val_list:  '/public/datasets/something/something_v2/something_v2_2/something_v2_rgb_val2.txt' #
    label_list:  'lists/something_v2_labels.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 0  #2
        M: 0  #9
    random_shift: false
network:
    arch: ViT-B/32  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_sthv2(2)
    sim_header: "Transf"  #Transf   meanP  LSTM Conv_1D Transf_cls
    joint: False
    describe:
solver:
    type: multistep
    epochs: 70
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.0005
    lr_decay_step: [15,30,50, 60]
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: false
    ratio: 1
    f_ratio: 5
logging:
    print_freq: 10
    eval_freq: 1